SR80:
  hardware_interface:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    loop_hz: 50

ads_config:
# remote_ipv4: "169.254.186.54"  
  remote_ipv4: "192.168.225.129"
# remote_net_id: "172.18.212.67.1.1"                       #"41.118.185.65.1.1"
  remote_net_id: "41.118.185.65.1.1"
